# Generated by Django 5.1 on 2024-10-16 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mp3file',
            name='transcription_date',
        ),
        migrations.AddField(
            model_name='mp3file',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mp3file',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mp3file',
            name='found_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mp3file',
            name='transcription_text',
            field=models.TextField(),
        ),
    ]
