# Generated by Django 5.1 on 2024-10-16 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_mp3file_transcription_date_mp3file_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3_file', models.URLField(verbose_name='Audio File')),
                ('url', models.URLField()),
                ('transcription_text', models.TextField()),
                ('duration', models.FloatField()),
                ('found_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('related_to_depression', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='MP3File',
        ),
    ]
