# Generated by Django 5.1 on 2024-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_audiofile_delete_mp3file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='mp3_file',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='local_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='found_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
