# Generated by Django 5.1 on 2024-10-22 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_audiofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='local_file',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='mp3_file',
            field=models.URLField(default=1, verbose_name='Audio File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='found_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='url',
            field=models.URLField(),
        ),
    ]
